[tool.poetry]
name = "automines"
version = "0.1.0"
description = ""
authors = ["Adri√°n Arroyo Calle <adrian.arroyocalle@gmail.com>"]
license = "EUPL-1.2"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
